In [280]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_pickle('prepared.pkl')


In [4]:
df.head()

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict cultur cla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base novel secret ag...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur sciencefict base novel mar med...


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      4806 non-null   int64 
 1   title   4806 non-null   object
 2   tags    4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 150.2+ KB


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [186]:
cv = CountVectorizer(max_features=5000 , stop_words='english' )

In [188]:
vectors = cv.fit_transform(df['tags']).toarray()

In [190]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [192]:
vectors.shape

(4806, 5000)

In [194]:
from sklearn.metrics.pairwise import cosine_similarity

In [196]:
new = cosine_similarity(vectors)

In [197]:
new.shape

(4806, 4806)

In [198]:
new

array([[1.        , 0.072393  , 0.05249442, ..., 0.07725291, 0.01853442,
        0.        ],
       [0.072393  , 1.        , 0.04496938, ..., 0.05956087, 0.        ,
        0.        ],
       [0.05249442, 0.04496938, 1.        , ..., 0.03839062, 0.        ,
        0.        ],
       ...,
       [0.07725291, 0.05956087, 0.03839062, ..., 1.        , 0.04066418,
        0.02033209],
       [0.01853442, 0.        , 0.        , ..., 0.04066418, 1.        ,
        0.02439024],
       [0.        , 0.        , 0.        , ..., 0.02033209, 0.02439024,
        1.        ]])

In [202]:
new[3]

array([0.04505773, 0.02894905, 0.097962  , ..., 0.08649889, 0.04447007,
       0.04447007])

In [204]:
df

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict cultur cla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base novel secret ag...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur sciencefict base novel mar med...
...,...,...,...
4804,9367,El Mariachi,action crime thriller unit barrier leg arm pap...
4805,72766,Newlyweds,comedi romanc newlyw coupl honeymoon upend arr...
4806,231617,"Signed, Sealed, Delivered",comedi drama romanc tvmovi date love first sig...
4807,126186,Shanghai Calling,ambiti new york attorney sam sent shanghai ass...


In [208]:
small_df=df[df['title']== 'The Dark Knight Rises']

In [210]:
small_df


,id,title,tags
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...


In [220]:
index=small_df.index[0]

In [222]:
index

3

In [224]:
new[3]

array([0.04505773, 0.02894905, 0.097962  , ..., 0.08649889, 0.04447007,
       0.04447007])

In [228]:
result = new[index]

In [230]:
result

array([0.04505773, 0.02894905, 0.097962  , ..., 0.08649889, 0.04447007,
       0.04447007])

In [232]:
indexed_tuples = list(enumerate(result))


In [240]:
indexed_tuples

[(0, 0.0450577320034842),
 (1, 0.02894904747440331),
 (2, 0.097961998115667),
 (3, 0.9999999999999999),
 (4, 0.023916533444472504),
 (5, 0.08306935378835814),
 (6, 0.04142465106674667),
 (7, 0.09885587665260744),
 (8, 0.033557802760701215),
 (9, 0.2573251177328327),
 (10, 0.06645435190240832),
 (11, 0.09303609266337166),
 (12, 0.015819299929208316),
 (13, 0.009738155563505966),
 (14, 0.08800333341388332),
 (15, 0.044743737014268294),
 (16, 0.08878560065057217),
 (17, 0.012054318600381366),
 (18, 0.08048843706309877),
 (19, 0.022853039006368696),
 (20, 0.0563883874434601),
 (21, 0.05789809494880662),
 (22, 0.0),
 (23, 0.015819299929208316),
 (24, 0.07679066282306657),
 (25, 0.08629149281323169),
 (26, 0.07749842582921285),
 (27, 0.026213122777949856),
 (28, 0.03427955850955304),
 (29, 0.09863939238321436),
 (30, 0.13829095250753096),
 (31, 0.11624763874381927),
 (32, 0.021919864974047635),
 (33, 0.06818952339930237),
 (34, 0.0),
 (35, 0.03465834966066909),
 (36, 0.044743737014268294),
 

In [246]:
sorted_tuples = sorted(indexed_tuples, reverse=True , key=lambda x: x[1])


In [250]:
sorted_tuples

[(3, 0.9999999999999999),
 (65, 0.5287626450141392),
 (119, 0.45605573451808834),
 (1361, 0.4487102358532513),
 (1360, 0.4291916612398504),
 (299, 0.3958977750648687),
 (428, 0.3835976370458338),
 (210, 0.34896554179912415),
 (1666, 0.33016512385321534),
 (3823, 0.33016512385321534),
 (4641, 0.2847473987257497),
 (2509, 0.27921779664372753),
 (4069, 0.2613021337856053),
 (9, 0.2573251177328327),
 (3970, 0.23952695597013823),
 (2386, 0.23749574799830375),
 (1875, 0.23692415692169538),
 (590, 0.2349046193249085),
 (1742, 0.23433321342066496),
 (1248, 0.23159237979522648),
 (3593, 0.22894552281285702),
 (238, 0.228945522812857),
 (283, 0.21919864974047634),
 (3308, 0.21556326252803537),
 (286, 0.215375979032619),
 (782, 0.21476993766848776),
 (3731, 0.21356054904431226),
 (3946, 0.21104470372357967),
 (3718, 0.21010507881568247),
 (3509, 0.20860300411675306),
 (1490, 0.20712325533373332),
 (879, 0.20264333232082316),
 (4775, 0.20264333232082316),
 (3861, 0.20236116462908824),
 (1849, 0.20

In [324]:
counter=0
for i,v in sorted_tuples:
    counter=counter+1
    if counter>5:
        break
    print(df.iloc[i][1])
    

The Dark Knight Rises
The Dark Knight
Batman Begins
Batman
Batman


In [310]:
def closest_movies(movie):
    small_df=df[df['title']== movie]
    index=small_df.index[0]
    result = new[index]
    indexed_tuples = list(enumerate(result))
    sorted_tuples = sorted(indexed_tuples, reverse=True , key=lambda x: x[1])
    counter=0
    for i,v in sorted_tuples:
        counter=counter+1
        if counter>6:
            break
        if counter==1:
            continue
        print(df.iloc[i][1])

In [316]:
closest_movies('Olympus Has Fallen')

White House Down
Absolute Power
Air Force One
The Butler
Dick


In [332]:
import pickle


In [334]:
movies_list = df['title'].values  
similarity_matrix = new      
print("Saving movie list...")
with open('movies_list.pkl', 'wb') as f:
    pickle.dump(movies_list, f)

print("Saving similarity matrix...")
with open('similarity_matrix.pkl', 'wb') as f:
    pickle.dump(similarity_matrix, f)

print("Saving full dataframe...")
with open('movies_df.pkl', 'wb') as f:
    pickle.dump(df, f) 

print("Data preparation complete!")
print(f"Total movies: {len(movies_list)}")

Saving movie list...
Saving similarity matrix...
Saving full dataframe...
Data preparation complete!
Total movies: 4806
