In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_pickle('prepared.pkl')


In [3]:
df.head()

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict cultur cla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base novel secret ag...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur sciencefict base novel mar med...


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      4806 non-null   int64 
 1   title   4806 non-null   object
 2   tags    4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 150.2+ KB


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer(max_features=5000 , stop_words='english' )

In [7]:
vectors = cv.fit_transform(df['tags']).toarray()

In [8]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [9]:
vectors.shape

(4806, 5000)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
new = cosine_similarity(vectors)

In [12]:
new.shape

(4806, 4806)

In [13]:
new

array([[1.        , 0.07188852, 0.0521286 , ..., 0.07671455, 0.01840525,
        0.        ],
       [0.07188852, 1.        , 0.04496938, ..., 0.05956087, 0.        ,
        0.        ],
       [0.0521286 , 0.04496938, 1.        , ..., 0.03839062, 0.        ,
        0.        ],
       ...,
       [0.07671455, 0.05956087, 0.03839062, ..., 1.        , 0.04066418,
        0.02033209],
       [0.01840525, 0.        , 0.        , ..., 0.04066418, 1.        ,
        0.02439024],
       [0.        , 0.        , 0.        , ..., 0.02033209, 0.02439024,
        1.        ]], shape=(4806, 4806))

In [14]:
new[3]

array([0.0455724 , 0.02948519, 0.09977626, ..., 0.08810086, 0.04529366,
       0.04529366], shape=(4806,))

In [15]:
df

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict cultur cla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drug abus exot i...
2,206647,Spectre,action adventur crime spi base novel secret ag...
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,49529,John Carter,action adventur sciencefict base novel mar med...
...,...,...,...
4804,9367,El Mariachi,action crime thriller unit state mexico barrie...
4805,72766,Newlyweds,comedi romanc newlyw coupl honeymoon upend arr...
4806,231617,"Signed, Sealed, Delivered",comedi drama romanc tvmovi date love first sig...
4807,126186,Shanghai Calling,ambiti new york attorney sam sent shanghai ass...


In [16]:
small_df=df[df['title']== 'The Dark Knight Rises']

In [17]:
small_df


,id,title,tags
3,49026,The Dark Knight Rises,action crime drama thriller dc comic crime fig...


In [18]:
index=small_df.index[0]

In [19]:
index

np.int64(3)

In [20]:
new[3]

array([0.0455724 , 0.02948519, 0.09977626, ..., 0.08810086, 0.04529366,
       0.04529366], shape=(4806,))

In [21]:
result = new[index]

In [22]:
result

array([0.0455724 , 0.02948519, 0.09977626, ..., 0.08810086, 0.04529366,
       0.04529366], shape=(4806,))

In [23]:
indexed_tuples = list(enumerate(result))


In [24]:
indexed_tuples

[(0, np.float64(0.04557239513497755)),
 (1, np.float64(0.029485186493565085)),
 (2, np.float64(0.09977626332184694)),
 (3, np.float64(1.0)),
 (4, np.float64(0.02416841222614159)),
 (5, np.float64(0.08460780585321008)),
 (6, np.float64(0.04270327431902071)),
 (7, np.float64(0.1006866965714241)),
 (8, np.float64(0.03417929635123316)),
 (9, np.float64(0.2599336399268469)),
 (10, np.float64(0.06768509260569024)),
 (11, np.float64(0.09475912964796633)),
 (12, np.float64(0.01589304997902437)),
 (13, np.float64(0.009918507099316576)),
 (14, np.float64(0.08963316323475065)),
 (15, np.float64(0.04557239513497755)),
 (16, np.float64(0.09042991813254031)),
 (17, np.float64(0.012179734920697825)),
 (18, np.float64(0.0819790903130556)),
 (19, np.float64(0.023276279388580713)),
 (20, np.float64(0.05771632558400802)),
 (21, np.float64(0.0582964037329089)),
 (22, np.float64(0.0)),
 (23, np.float64(0.016112274817427726)),
 (24, np.float64(0.07821283295433408)),
 (25, np.float64(0.08744460559936333)),
 

In [25]:
sorted_tuples = sorted(indexed_tuples, reverse=True , key=lambda x: x[1])


In [26]:
sorted_tuples

[(3, np.float64(1.0)),
 (65, np.float64(0.5251503739235127)),
 (119, np.float64(0.4622847229890194)),
 (1361, np.float64(0.4570203906502589)),
 (1360, np.float64(0.43714033024158544)),
 (428, np.float64(0.39070190053016324)),
 (299, np.float64(0.37528515565469767)),
 (210, np.float64(0.3554284156973712)),
 (1666, np.float64(0.3362798122836586)),
 (3823, np.float64(0.3362798122836586)),
 (2509, np.float64(0.2900209467136991)),
 (4641, np.float64(0.29002094671369905)),
 (4069, np.float64(0.2734343708098653)),
 (9, np.float64(0.2599336399268469)),
 (3970, np.float64(0.2439630172032473)),
 (2386, np.float64(0.24189419107314025)),
 (1875, np.float64(0.24131201407727337)),
 (590, np.float64(0.23925507445863212)),
 (1742, np.float64(0.2386730860645393)),
 (1248, np.float64(0.23588149194852065)),
 (238, np.float64(0.2343723178370274)),
 (3593, np.float64(0.2331856149316356)),
 (283, np.float64(0.22325822887437896)),
 (286, np.float64(0.22054098894820123)),
 (3308, np.float64(0.2195555139567319

In [27]:
counter=0
for i,v in sorted_tuples:
    counter=counter+1
    if counter>5:
        break
    print(df.iloc[i][1])
    

The Dark Knight Rises
The Dark Knight
Batman Begins
Batman
Batman


In [28]:
def closest_movies(movie):
    small_df=df[df['title']== movie]
    index=small_df.index[0]
    result = new[index]
    indexed_tuples = list(enumerate(result))
    sorted_tuples = sorted(indexed_tuples, reverse=True , key=lambda x: x[1])
    counter=0
    for i,v in sorted_tuples:
        counter=counter+1
        if counter>6:
            break
        if counter==1:
            continue
        print(df.iloc[i][1])

In [29]:
closest_movies('Olympus Has Fallen')

White House Down
Absolute Power
Air Force One
The Butler
London Has Fallen


In [30]:
import pickle


In [31]:
movies_list = df['title'].values  
similarity_matrix = new      
print("Saving movie list...")
with open('movies_list.pkl', 'wb') as f:
    pickle.dump(movies_list, f)

print("Saving similarity matrix...")
with open('similarity_matrix.pkl', 'wb') as f:
    pickle.dump(similarity_matrix, f)

print("Saving full dataframe...")
with open('movies_df.pkl', 'wb') as f:
    pickle.dump(df, f) 

print("Data preparation complete!")
print(f"Total movies: {len(movies_list)}")

Saving movie list...
Saving similarity matrix...
Saving full dataframe...
Data preparation complete!
Total movies: 4806


In [32]:
import gzip
import pickle

# Compress and save the similarity matrix
with gzip.open('similarity_matrix.pkl.gz', 'wb') as f:
    pickle.dump(similarity_matrix, f) 
print("Compression complete!")

Compression complete!
